// Seung Eun Lee
// 2018-07-04
//range 0~100

/**
The program randomly generates an integer greater than or
equal to 0 and less than 100. The program then prompts the user
to guess the number.
• If the user guesses the number correctly, the program outputs
an appropriate message with the number of guesses that the
user made.
• If the guessed number is less than the random number
generated by the program, the program outputs the message
"Your guess is lower than the number. Guess again!";
• Otherwise, the program outputs the message "Your guess is
higher than the number. Guess again!".
• The program then prompts the user to enter another number.
The user is prompted to guess the random number until the user
enters the correct number. 

**/

#include <iostream>
#include <cstdlib>
#include <ctime>
using namespace std;

int main()
{
    int target,guess;
    int count=0;
    bool isDone = false;
    
    //decide a number randomly
    srand(time(0));
    target= rand()%101;
    
    // loop until the one gets correct answer
    
    while (!isDone)
    {   cout << "What's your guess [0 - 100] ?: ";
        cin >>guess;
        count++; //the count is increased by 1 after the each guess
        if (guess==target)
        {  cout << "You got it by "<<count<<" guesses.\n";
            isDone=true;
        }
        else if (guess < target)
        cout << "Your guess is lower than the number. Guess again! \n";
        else
        cout << "Your guess is higher than the number. Guess again! \n";
    
    }
    
    return 0;
    
}
